name: Run Tests on Main Push

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Select Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Bundle Install
        run: bundle install
      - name: Run Tests
        run: bundle exec fastlane scan
